Bar Blogger/Bar Blogger/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bar_Blogger;

namespace Bar_Blogger.Controllers
{
    public class BlogsController : Controller
    {
        private GitDrunkEntities db = new GitDrunkEntities();

        // GET: Blogs
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: Blogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Blog_Title,Blog_Author,Blog_Content,Blog_Date,Blog_Rating,Blog_ID,Blog_Location,Blog_City,Blog_State")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blog);
        }
        [Authorize]
        // GET: Blogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Blog_Title,Blog_Author,Blog_Content,Blog_Date,Blog_Rating,Blog_ID,Blog_Location,Blog_City,Blog_State")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        [Authorize]
        // GET: Blogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Blogs.Find(id);
            db.Blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bar Blogger/Bar Blogger/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bar_Blogger.Controllers
{
    public class HomeController : Controller
    {
        private GitDrunkEntities db = new GitDrunkEntities();

        public ActionResult Index()
        {
            return View(db.Blogs.Take(3).ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bar Blogger/Bar Blogger/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Bar Blogger/Bar Blogger/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h1>Team Members:</h1>

<h3>Huy Le</h3>
<h3>Kha Le</h3>
<h3>Corbin Skelton</h3>
<h3>Mark Smith</h3>
<h3>Trung Tran</h3>

Bar Blogger/Bar Blogger/Views/Home/Index.cshtml
@model IEnumerable<Bar_Blogger.Blog>

@{
    ViewBag.Title = "Home Page";
}

<div style="background-image: url('../../Images/bg_beer.jpg')" class="jumbotron">
        <h1 style="color: antiquewhite">Welcome to GitDrunk!</h1>
        <p style="color: antiquewhite" class="lead">Here we be bloggin <br> bout groggin.</p>
</div>


<div class="row">
    <h2>Reviews</h2>
        
    @foreach (var bar in Model)
    {
        <div class="col-xs-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Html.DisplayFor(modelItem => bar.Blog_Title) | <span class="author">@Html.DisplayFor(modelItem => bar.Blog_Author)</span>
                    <span class="pull-right">@Html.ActionLink("Details", "Details", "Blogs", new { id = bar.Blog_ID }, new { @class = "btn btn-default detail-btn glyphicon glyphicon-glass" })</span> @*<button class="btn btn-default pull-right glyphicon glyphicon-glass detail-btn"></button>*@
                </div>
                <div class="panel-body">
                    <p>@Html.DisplayFor(modelItem => bar.Blog_Content)</p>
                </div>
            </div>
        </div>
    }
    <p class="col-xs-9">@Html.ActionLink("Browse All Reviews", "Index", "Blogs", new { area = "" }, new { @class = "btn-warning btn-lg" })</p>

</div>

<div class="row">
    <div class="col-xs-6">
        <h2>Blog</h2>
        <p>Be bloggin 'bout your groggin.</p>
        <p>@Html.ActionLink("Write", "Create", "Blogs", new { area = "" }, new { @class = "btn-warning btn-lg" })</p>
    </div>
    <div class="col-xs-6">
        <h2>Donate</h2>
        <p>We want to drink too.</p>
        <p>@Html.ActionLink("Donate", "#", new { area = "" }, new { @class = "btn-warning btn-lg" })</p>
    </div>
</div>